import { StrategyOption, VaultRow } from "./types";

export const MOCK_STRATEGIES: StrategyOption[] = [
  {
    id: "mom-alpha",
    name: "Momentum Alpha",
    key: "MOM-ALPHA",
    chainName: "Ethereum",
    dexName: "Uniswap V3",
    poolAddressShort: "0x8ad...2913",
    pairLabel: "ETH/USDC",
    adapterStatus: "ok",
    gaugeStatus: "none",
  },
  {
    id: "btc-rebal",
    name: "BTC Rebal Core",
    key: "BTC-REBAL",
    chainName: "Polygon",
    dexName: "QuickSwap",
    poolAddressShort: "0x2c1...77a0",
    pairLabel: "WBTC/USDC",
    adapterStatus: "ok",
    gaugeStatus: "none",
  },
  {
    id: "eth-grid",
    name: "ETH Grid Bot",
    key: "ETH-GRID",
    chainName: "Ethereum",
    dexName: "Uniswap V3",
    poolAddressShort: "0x1f9...0b2c",
    pairLabel: "ETH/USDC",
    adapterStatus: "missing",
    gaugeStatus: "none",
  },
];

export const MOCK_VAULTS: VaultRow[] = [
  {
    id: "vault_1",
    alias: "Alpha Vault One",
    subtitle: "Personal Savings",
    vaultAddress: "0x7a000000000000000000000000000000009f2b",
    strategyName: "Momentum Alpha",
    strategyKey: "MOM-ALPHA",
    chainName: "Ethereum",
    dexName: "Uniswap V3",
    pairLabel: "ETH/USDC",
    token0Symbol: "ETH",
    token1Symbol: "USDC",
    health: "healthy",
    updatedAtLabel: "10 mins ago",
    explorerUrl: "#",
  },
  {
    id: "vault_2",
    alias: "BTC Accumulator",
    subtitle: "Long term hold",
    vaultAddress: "0x3c000000000000000000000000000000008d14",
    strategyName: "BTC Rebal Core",
    strategyKey: "BTC-REBAL",
    chainName: "Polygon",
    dexName: "QuickSwap",
    pairLabel: "WBTC/USDC",
    token0Symbol: "WBTC",
    token1Symbol: "USDC",
    health: "warning",
    updatedAtLabel: "2 days ago",
    explorerUrl: "#",
  },
];