import type {
  ActivePositionRow,
  OperationalWarning,
  RuntimeHighlightRow,
  TradeSignalRow,
  TradeStrategyRow,
} from "./types";

export const TRADE_HOME_STRATEGIES: TradeStrategyRow[] = [
  {
    id: "strat_8291",
    name: "BTC Momentum v2",
    symbol: "BTC/USDT",
    streamKey: "binance_btcusdt_5m",
    strategyType: "momentum",
    executionAccount: "#acc_1234",
    status: "active",
    updatedAtLabel: "2 mins ago",
  },
  {
    id: "strat_8292",
    name: "ETH Breakout",
    symbol: "ETH/USDT",
    streamKey: "binance_ethusdt_15m",
    strategyType: "breakout",
    executionAccount: "#acc_1234",
    status: "active",
    updatedAtLabel: "5 mins ago",
  },
  {
    id: "strat_8293",
    name: "SOL Mean Reversion",
    symbol: "SOL/USDT",
    streamKey: "binance_solusdt_5m",
    strategyType: "mean_reversion",
    executionAccount: "#acc_5678",
    status: "active",
    updatedAtLabel: "8 mins ago",
  },
  {
    id: "strat_8294",
    name: "MATIC Grid",
    symbol: "MATIC/USDT",
    streamKey: "binance_maticusdt_1h",
    strategyType: "grid",
    executionAccount: "#acc_5678",
    status: "paused",
    updatedAtLabel: "1 hour ago",
  },
  {
    id: "strat_8295",
    name: "AVAX Trend",
    symbol: "AVAX/USDT",
    streamKey: "binance_avaxusdt_15m",
    strategyType: "trend_following",
    executionAccount: null,
    status: "active",
    updatedAtLabel: "4 mins ago",
  },
  {
    id: "strat_8296",
    name: "LINK Reversal",
    symbol: "LINK/USDT",
    streamKey: "binance_linkusdt_5m",
    strategyType: "reversal",
    executionAccount: null,
    status: "active",
    updatedAtLabel: "11 mins ago",
  },
  {
    id: "strat_8297",
    name: "DOGE Scalper",
    symbol: "DOGE/USDT",
    streamKey: "binance_dogeusdt_1m",
    strategyType: "scalping",
    executionAccount: null,
    status: "failed",
    updatedAtLabel: "18 mins ago",
  },
];

export const TRADE_HOME_RUNTIME_HIGHLIGHTS: RuntimeHighlightRow[] = [
  {
    strategyId: "strat_8291",
    symbol: "BTC/USDT",
    runtimeState: "in_position",
    event: "entry_long",
    atr: "1,245.50",
    atrPct: "2.8%",
    setupArmed: false,
    desiredSide: "long",
    positionSide: "long",
    barsSinceEvent: 42,
    updatedAtLabel: "1 min ago",
  },
  {
    strategyId: "strat_8292",
    symbol: "ETH/USDT",
    runtimeState: "waiting_setup",
    event: "none",
    atr: "82.30",
    atrPct: "3.2%",
    setupArmed: true,
    desiredSide: "short",
    positionSide: "none",
    barsSinceEvent: 18,
    updatedAtLabel: "2 mins ago",
  },
  {
    strategyId: "strat_8293",
    symbol: "SOL/USDT",
    runtimeState: "in_position",
    event: "exit_short",
    atr: "3.45",
    atrPct: "4.1%",
    setupArmed: false,
    desiredSide: "none",
    positionSide: "short",
    barsSinceEvent: 7,
    updatedAtLabel: "5 mins ago",
  },
  {
    strategyId: "strat_8295",
    symbol: "AVAX/USDT",
    runtimeState: "idle_no_account",
    event: "none",
    atr: "1.92",
    atrPct: "3.7%",
    setupArmed: true,
    desiredSide: "long",
    positionSide: "none",
    barsSinceEvent: 25,
    updatedAtLabel: "12 mins ago",
  },
  {
    strategyId: "strat_8296",
    symbol: "LINK/USDT",
    runtimeState: "stale_runtime",
    event: "none",
    atr: "0.67",
    atrPct: "2.4%",
    setupArmed: false,
    desiredSide: "none",
    positionSide: "none",
    barsSinceEvent: 140,
    updatedAtLabel: "14 mins ago",
  },
];

export const TRADE_HOME_ACTIVE_POSITIONS: ActivePositionRow[] = [
  {
    id: "pos_1001",
    symbol: "BTC/USDT",
    strategyId: "strat_8291",
    executionAccount: "#acc_1234",
    positionSide: "long",
    status: "open",
    quantity: "0.50 BTC",
    entryPrice: "$44,250.00",
    openedAt: "2024-01-15 14:30:00",
  },
  {
    id: "pos_1002",
    symbol: "ETH/USDT",
    strategyId: "strat_8292",
    executionAccount: "#acc_1234",
    positionSide: "short",
    status: "open",
    quantity: "10 ETH",
    entryPrice: "$2,580.00",
    openedAt: "2024-01-15 10:15:00",
  },
  {
    id: "pos_1003",
    symbol: "SOL/USDT",
    strategyId: "strat_8293",
    executionAccount: "#acc_5678",
    positionSide: "long",
    status: "open",
    quantity: "500 SOL",
    entryPrice: "$84.20",
    openedAt: "2024-01-14 16:45:00",
  },
];

export const TRADE_HOME_SIGNALS: TradeSignalRow[] = [
  {
    id: "sig_9001",
    strategyId: "strat_8291",
    symbol: "BTC/USDT",
    signalType: "entry_long",
    status: "pending",
    timestamp: "2024-01-15 14:28:45",
    attempts: 1,
    lastError: null,
  },
  {
    id: "sig_9002",
    strategyId: "strat_8294",
    symbol: "MATIC/USDT",
    signalType: "exit_long",
    status: "failed",
    timestamp: "2024-01-15 14:20:12",
    attempts: 3,
    lastError: "Insufficient balance",
  },
  {
    id: "sig_9003",
    strategyId: "strat_8295",
    symbol: "AVAX/USDT",
    signalType: "entry_short",
    status: "completed",
    timestamp: "2024-01-15 14:15:30",
    attempts: 1,
    lastError: null,
  },
  {
    id: "sig_9004",
    strategyId: "strat_8296",
    symbol: "LINK/USDT",
    signalType: "exit_short",
    status: "pending",
    timestamp: "2024-01-15 14:10:05",
    attempts: 2,
    lastError: null,
  },
  {
    id: "sig_9005",
    strategyId: "strat_8297",
    symbol: "DOGE/USDT",
    signalType: "entry_long",
    status: "failed",
    timestamp: "2024-01-15 13:58:11",
    attempts: 2,
    lastError: "Execution profile disabled",
  },
];

export const TRADE_HOME_WARNINGS: OperationalWarning[] = [
  {
    id: "warning_failed_signals",
    tone: "red",
    title: "2 Failed Signals Detected",
    description:
      "Recent signals have failed execution. Review execution profiles and account balances.",
    ctaLabel: "View Failed Signals",
  },
  {
    id: "warning_missing_accounts",
    tone: "orange",
    title: "3 Strategies Without Execution Account",
    description:
      "Some active strategies are not linked to an execution account and cannot place orders.",
    ctaLabel: "Review Strategies",
  },
  {
    id: "warning_disabled_profile",
    tone: "yellow",
    title: "1 Execution Profile Disabled",
    description:
      "An execution profile used by active strategies is currently disabled.",
    ctaLabel: "View Execution Profiles",
  },
  {
    id: "warning_stale_runtime",
    tone: "blue",
    title: "2 Strategies With No Recent Runtime Updates",
    description:
      "Active strategies have not reported runtime state in over 10 minutes. Check market stream connectivity.",
    ctaLabel: "Check Strategies",
  },
];

export const TRADE_HOME_METADATA = {
  enabledExecutionProfiles: 5,
};