import type { DexOption, PoolOption, MyStrategyRow } from "./types";

export const DEX_OPTIONS: DexOption[] = [
  { id: "uniswap_v3", name: "Uniswap V3" },
  { id: "curve", name: "Curve" },
  { id: "quickswap", name: "QuickSwap" },
];

export const POOL_OPTIONS: PoolOption[] = [
  {
    id: "pool_eth_usdc_005",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    token0Symbol: "ETH",
    token1Symbol: "USDC",
    pairLabel: "ETH/USDC",
    feeLabel: "0.05%",
    adapterAddress: "0x7a2e...9b3c",
    routerAddress: "0x3f1...8e2d",
    gaugeAvailable: true,
  },
  {
    id: "pool_wbtc_usdc_03",
    dexId: "quickswap",
    dexName: "QuickSwap",
    token0Symbol: "WBTC",
    token1Symbol: "USDC",
    pairLabel: "WBTC/USDC",
    feeLabel: "0.3%",
    adapterAddress: "0x12aa...43d1",
    routerAddress: "0x9c01...11f2",
    gaugeAvailable: false,
  },
  {
    id: "pool_usdc_usdt_001",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    token0Symbol: "USDC",
    token1Symbol: "USDT",
    pairLabel: "USDC/USDT",
    feeLabel: "0.01%",
    adapterAddress: "0x4b8c...7e9a",
    routerAddress: "0x8c31...2aa1",
    gaugeAvailable: true,
  },
];

export const MOCK_MY_STRATEGIES: MyStrategyRow[] = [
  {
    id: 24,
    name: "Momentum Alpha",
    symbol: "MOM-ALPHA",
    dexName: "Uniswap V3",
    poolPairLabel: "ETH/USDC",
    feeLabel: "0.05%",
    token0Symbol: "ETH",
    token1Symbol: "USDC",
    status: "ACTIVE",
    updatedAtLabel: "2h ago",
    indicatorSetId: "cfg_0x7a2e...9b3c",
    indicatorSource: "binance",
    emaFast: 10,
    emaSlow: 50,
    atrWindow: 20,
    chainKey: "ethereum",
    chainName: "Ethereum",
    vaultLabel: "Vault #12",
  },
  {
    id: 23,
    name: "BTC Rebal Core",
    symbol: "BTC-REBAL",
    dexName: "QuickSwap",
    poolPairLabel: "WBTC/USDC",
    feeLabel: "0.3%",
    token0Symbol: "WBTC",
    token1Symbol: "USDC",
    status: "INACTIVE",
    updatedAtLabel: "2d ago",
    indicatorSetId: "cfg_0x9f3a...2c1d",
    indicatorSource: "binance",
    emaFast: 12,
    emaSlow: 26,
    atrWindow: 14,
    chainKey: "polygon",
    chainName: "Polygon",
    vaultLabel: null,
  },
  {
    id: 22,
    name: "Range Optimizer",
    symbol: "RANGE-OPT",
    dexName: "Uniswap V3",
    poolPairLabel: "USDC/USDT",
    feeLabel: "0.01%",
    token0Symbol: "USDC",
    token1Symbol: "USDT",
    status: "ACTIVE",
    updatedAtLabel: "5h ago",
    indicatorSetId: "cfg_0x4b8c...7e9a",
    indicatorSource: "coinbase",
    emaFast: 20,
    emaSlow: 50,
    atrWindow: 30,
    chainKey: "ethereum",
    chainName: "Ethereum",
    vaultLabel: "Vault #8",
  },
  {
    id: 21,
    name: "ETH Trend Core",
    symbol: "ETH-TREND",
    dexName: "Uniswap V3",
    poolPairLabel: "ETH/USDC",
    feeLabel: "0.05%",
    token0Symbol: "ETH",
    token1Symbol: "USDC",
    status: "ACTIVE",
    updatedAtLabel: "1d ago",
    indicatorSetId: "cfg_0x6d12...88ab",
    indicatorSource: "binance",
    emaFast: 9,
    emaSlow: 21,
    atrWindow: 14,
    chainKey: "base",
    chainName: "Base",
    vaultLabel: null,
  },
];