import { AllocationSlice, PortfolioKpis, PortfolioPosition } from "./types";

export const MOCK_KPIS: PortfolioKpis = {
  totalDepositedUsd: 124_592.45,
  currentValueUsd: 132_832.1,
  netProfitUsd: 8_240,
  netProfitPct: 6.61,

  unclaimedRewardsUsd: 1_240.85,

  avgApyPct: 12.4,
  avgAprPct: 10.8,

  activePositions: 4,
  totalPositions: 6,
};

export const MOCK_POSITIONS_ACTIVE: PortfolioPosition[] = [
  {
    id: "pos_1",
    vaultName: "Delta Neutral LP",
    pairLabel: "WETH/USDC",
    risk: "low",
    depositedUsd: 50_000,
    depositedSubLabel: "25.4 ETH",
    currentValueUsd: 53_240.5,
    profitUsd: 3_240.5,
    profitPct: 6.48,
    apyPct: 14.8,
    aprPct: 12.4,
    status: "active",
    iconVariant: "blueCyan",
  },
  {
    id: "pos_2",
    vaultName: "BTC Yield Max",
    pairLabel: "WBTC/USDC",
    risk: "medium",
    depositedUsd: 45_000,
    depositedSubLabel: "1.2 WBTC",
    currentValueUsd: 47_890.1,
    profitUsd: 2_890.1,
    profitPct: 6.42,
    apyPct: 9.5,
    aprPct: 8.2,
    status: "active",
    iconVariant: "orangeRed",
  },
  {
    id: "pos_3",
    vaultName: "Stable Reserve",
    pairLabel: "USDC/USDT",
    risk: "low",
    depositedUsd: 20_000,
    depositedSubLabel: "20k USDC",
    currentValueUsd: 21_800.5,
    profitUsd: 1_800.5,
    profitPct: 9.0,
    apyPct: 5.2,
    aprPct: 4.8,
    status: "active",
    iconVariant: "purpleIndigo",
  },
  {
    id: "pos_4",
    vaultName: "Experimental V2",
    pairLabel: "ETH/LINK",
    risk: "high",
    depositedUsd: 9_592.45,
    depositedSubLabel: "4.8 ETH",
    currentValueUsd: 9_901.0,
    profitUsd: 308.55,
    profitPct: 3.21,
    apyPct: 18.5,
    aprPct: 15.2,
    status: "paused",
    iconVariant: "slate",
  },
];

export const MOCK_POSITIONS_HISTORY: PortfolioPosition[] = [
  {
    id: "pos_h_1",
    vaultName: "Old ETH Range",
    pairLabel: "WETH/USDC",
    risk: "medium",
    depositedUsd: 12_000,
    depositedSubLabel: "6.2 ETH",
    currentValueUsd: 11_420,
    profitUsd: -580,
    profitPct: -4.83,
    apyPct: 0,
    aprPct: 0,
    status: "closed",
    iconVariant: "blueCyan",
  },
  {
    id: "pos_h_2",
    vaultName: "Stable Carry",
    pairLabel: "USDC/DAI",
    risk: "low",
    depositedUsd: 8_500,
    depositedSubLabel: "8.5k USDC",
    currentValueUsd: 8_910,
    profitUsd: 410,
    profitPct: 4.82,
    apyPct: 0,
    aprPct: 0,
    status: "closed",
    iconVariant: "purpleIndigo",
  },
];

export const MOCK_ALLOCATION: AllocationSlice[] = [
  { id: "alloc_1", label: "Delta Neutral LP", pct: 40.1, color: "#3b82f6" },
  { id: "alloc_2", label: "BTC Yield Max", pct: 36.1, color: "#f97316" },
  { id: "alloc_3", label: "Stable Reserve", pct: 16.4, color: "#22c55e" },
  { id: "alloc_4", label: "Experimental V2", pct: 7.4, color: "#64748b" },
];