import { ChainOption, DexOption, VaultExploreItem } from "./types";

export const CHAINS: ChainOption[] = [
  { id: "all", name: "All Chains" },
  { id: "ethereum", name: "Ethereum" },
  { id: "polygon", name: "Polygon" },
  { id: "arbitrum", name: "Arbitrum" },
  { id: "optimism", name: "Optimism" },
];

export const DEXES: DexOption[] = [
  { id: "all", name: "All DEXs" },
  { id: "uniswap_v3", name: "Uniswap V3" },
  { id: "pancakeswap_v3", name: "PancakeSwap" },
  { id: "curve", name: "Curve" },
  { id: "quickswap", name: "QuickSwap" },
  { id: "velodrome", name: "Velodrome" },
];

export const MOCK_VAULTS: VaultExploreItem[] = [
  {
    id: "vault_usdc_eth_005",
    name: "USDC-ETH 0.05%",
    address: "0x88e6...2158",
    token0Symbol: "USDC",
    token1Symbol: "ETH",
    feeTierLabel: "0.05%",
    pairType: "volatile",
    chainId: "ethereum",
    chainName: "Ethereum",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    tvlUsd: 14205892,
    tvlChange24hPct: 2.4,
    apyPct: 18.42,
    aprPct: 16.8,
    status: "active",
    favorited: false,
  },
  {
    id: "vault_wbtc_eth_03",
    name: "WBTC-ETH 0.3%",
    address: "0xcbcdf...92a1",
    token0Symbol: "WBTC",
    token1Symbol: "ETH",
    feeTierLabel: "0.3%",
    pairType: "volatile",
    chainId: "polygon",
    chainName: "Polygon",
    dexId: "quickswap",
    dexName: "QuickSwap",
    tvlUsd: 8942103,
    tvlChange24hPct: 0.0,
    apyPct: 12.05,
    aprPct: 11.2,
    status: "active",
    favorited: true,
  },
  {
    id: "vault_usdt_usdc_001",
    name: "USDT-USDC 0.01%",
    address: "0x72a...b49c",
    token0Symbol: "USDT",
    token1Symbol: "USDC",
    feeTierLabel: "0.01%",
    pairType: "stable",
    chainId: "arbitrum",
    chainName: "Arbitrum",
    dexId: "curve",
    dexName: "Curve",
    tvlUsd: 42891005,
    tvlChange24hPct: -1.2,
    apyPct: 4.85,
    aprPct: 4.2,
    status: "paused",
    favorited: false,
  },
  {
    id: "vault_eth_uni_03",
    name: "ETH-UNI 0.3%",
    address: "0x1d4...8e2f",
    token0Symbol: "ETH",
    token1Symbol: "UNI",
    feeTierLabel: "0.3%",
    pairType: "volatile",
    chainId: "ethereum",
    chainName: "Ethereum",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    tvlUsd: 3102445,
    tvlChange24hPct: 0.8,
    apyPct: 24.1,
    aprPct: 21.5,
    status: "active",
    favorited: false,
  },
  {
    id: "vault_op_usdc_005",
    name: "OP-USDC 0.05%",
    address: "0x4a2...9c1d",
    token0Symbol: "OP",
    token1Symbol: "USDC",
    feeTierLabel: "0.05%",
    pairType: "volatile",
    chainId: "optimism",
    chainName: "Optimism",
    dexId: "velodrome",
    dexName: "Velodrome",
    tvlUsd: 1240500,
    tvlChange24hPct: 5.1,
    apyPct: 32.8,
    aprPct: 28.5,
    status: "active",
    favorited: false,
  },
];