import { ChainOption, DexOption, VaultExploreItem } from "./types";

export const CHAINS: ChainOption[] = [
  { id: "all", name: "All Chains" },
  { id: "base", name: "Base" },
  { id: "ethereum", name: "Ethereum" },
  { id: "polygon", name: "Polygon" },
  { id: "arbitrum", name: "Arbitrum" },
  { id: "optimism", name: "Optimism" },
];

export const DEXES: DexOption[] = [
  { id: "all", name: "All DEXs" },
  { id: "uniswap_v3", name: "Uniswap V3" },
  { id: "pancakeswap_v3", name: "PancakeSwap V3" },
  { id: "aerodrome", name: "Aerodrome" },
  { id: "curve", name: "Curve" },
  { id: "quickswap", name: "QuickSwap" },
  { id: "velodrome", name: "Velodrome" },
];

export const MOCK_VAULTS: VaultExploreItem[] = [
  {
    id: "vault_usdc_eth_005",
    name: "USDC-ETH 0.05%",
    address: "0x88e62158",
    token0Symbol: "USDC",
    token1Symbol: "ETH",
    feeTierLabel: "0.05%",
    pairType: "volatile",
    chainId: "ethereum",
    chainName: "Ethereum",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    tvlUsd: 14205892,
    tvlChange24hPct: 2.4,
    apyPct: 18.42,
    aprPct: 16.8,
    status: "active",
    rangeStatus: "inside",
    hasGauge: true,
    isMine: true,
    myPositionUsd: 12450,
    favorited: false,
  },
  {
    id: "vault_wbtc_eth_03",
    name: "WBTC-ETH 0.3%",
    address: "0xcbcdf92a1",
    token0Symbol: "WBTC",
    token1Symbol: "ETH",
    feeTierLabel: "0.3%",
    pairType: "volatile",
    chainId: "polygon",
    chainName: "Polygon",
    dexId: "quickswap",
    dexName: "QuickSwap",
    tvlUsd: 8942103,
    tvlChange24hPct: 0,
    apyPct: 12.05,
    aprPct: 11.2,
    status: "active",
    rangeStatus: "inside",
    hasGauge: true,
    isMine: true,
    myPositionUsd: 8920,
    favorited: true,
  },
  {
    id: "vault_usdt_usdc_001",
    name: "USDT-USDC 0.01%",
    address: "0x72ab49c",
    token0Symbol: "USDT",
    token1Symbol: "USDC",
    feeTierLabel: "0.01%",
    pairType: "stable",
    chainId: "arbitrum",
    chainName: "Arbitrum",
    dexId: "curve",
    dexName: "Curve",
    tvlUsd: 42891005,
    tvlChange24hPct: -1.2,
    apyPct: 4.85,
    aprPct: 4.2,
    status: "paused",
    rangeStatus: "inside",
    hasGauge: false,
    isMine: false,
    favorited: false,
  },
  {
    id: "vault_eth_uni_03",
    name: "ETH-UNI 0.3%",
    address: "0x1d48e2f",
    token0Symbol: "ETH",
    token1Symbol: "UNI",
    feeTierLabel: "0.3%",
    pairType: "volatile",
    chainId: "ethereum",
    chainName: "Ethereum",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    tvlUsd: 3102445,
    tvlChange24hPct: 0.8,
    apyPct: 24.1,
    aprPct: 21.5,
    status: "active",
    rangeStatus: "inside",
    hasGauge: false,
    isMine: true,
    myPositionUsd: 3100,
    favorited: false,
  },
  {
    id: "vault_op_usdc_005",
    name: "OP-USDC 0.05%",
    address: "0x4a29c1d",
    token0Symbol: "OP",
    token1Symbol: "USDC",
    feeTierLabel: "0.05%",
    pairType: "volatile",
    chainId: "optimism",
    chainName: "Optimism",
    dexId: "velodrome",
    dexName: "Velodrome",
    tvlUsd: 1240500,
    tvlChange24hPct: 5.1,
    apyPct: 32.8,
    aprPct: 28.5,
    status: "active",
    rangeStatus: "above",
    hasGauge: true,
    isMine: false,
    favorited: false,
  },
  {
    id: "vault_cbbtc_weth_03",
    name: "cbBTC-WETH 0.3%",
    address: "0x5f42b7e",
    token0Symbol: "cbBTC",
    token1Symbol: "WETH",
    feeTierLabel: "0.3%",
    pairType: "volatile",
    chainId: "base",
    chainName: "Base",
    dexId: "pancakeswap_v3",
    dexName: "PancakeSwap V3",
    tvlUsd: 2281400,
    tvlChange24hPct: 1.6,
    apyPct: 15.7,
    aprPct: 14.4,
    status: "active",
    rangeStatus: "inside",
    hasGauge: true,
    isMine: false,
    favorited: false,
  },
  {
    id: "vault_aero_usdc_005",
    name: "AERO-USDC 0.05%",
    address: "0x7ec0a11",
    token0Symbol: "AERO",
    token1Symbol: "USDC",
    feeTierLabel: "0.05%",
    pairType: "volatile",
    chainId: "base",
    chainName: "Base",
    dexId: "aerodrome",
    dexName: "Aerodrome",
    tvlUsd: 3512800,
    tvlChange24hPct: -0.6,
    apyPct: 27.2,
    aprPct: 23.9,
    status: "active",
    rangeStatus: "below",
    hasGauge: true,
    isMine: false,
    favorited: true,
  },
  {
    id: "vault_arb_usdc_005",
    name: "ARB-USDC 0.05%",
    address: "0x9bb41f2",
    token0Symbol: "ARB",
    token1Symbol: "USDC",
    feeTierLabel: "0.05%",
    pairType: "volatile",
    chainId: "arbitrum",
    chainName: "Arbitrum",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    tvlUsd: 1675900,
    tvlChange24hPct: -2.1,
    apyPct: 19.4,
    aprPct: 17.6,
    status: "deprecated",
    rangeStatus: "above",
    hasGauge: false,
    isMine: false,
    favorited: false,
  },
  {
    id: "vault_dai_usdc_001",
    name: "DAI-USDC 0.01%",
    address: "0x13da77c",
    token0Symbol: "DAI",
    token1Symbol: "USDC",
    feeTierLabel: "0.01%",
    pairType: "stable",
    chainId: "polygon",
    chainName: "Polygon",
    dexId: "quickswap",
    dexName: "QuickSwap",
    tvlUsd: 9824500,
    tvlChange24hPct: 0.2,
    apyPct: 6.7,
    aprPct: 6.1,
    status: "active",
    rangeStatus: "inside",
    hasGauge: false,
    isMine: false,
    favorited: false,
  },
  {
    id: "vault_weth_usdc_005",
    name: "WETH-USDC 0.05%",
    address: "0x61aa9bc",
    token0Symbol: "WETH",
    token1Symbol: "USDC",
    feeTierLabel: "0.05%",
    pairType: "volatile",
    chainId: "base",
    chainName: "Base",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    tvlUsd: 11634000,
    tvlChange24hPct: 3.2,
    apyPct: 14.9,
    aprPct: 13.7,
    status: "active",
    rangeStatus: "inside",
    hasGauge: false,
    isMine: false,
    favorited: false,
  },
  {
    id: "vault_gmx_eth_03",
    name: "GMX-ETH 0.3%",
    address: "0x8812ca0",
    token0Symbol: "GMX",
    token1Symbol: "ETH",
    feeTierLabel: "0.3%",
    pairType: "volatile",
    chainId: "arbitrum",
    chainName: "Arbitrum",
    dexId: "uniswap_v3",
    dexName: "Uniswap V3",
    tvlUsd: 745000,
    tvlChange24hPct: -3.4,
    apyPct: 29.6,
    aprPct: 25.2,
    status: "active",
    rangeStatus: "below",
    hasGauge: false,
    isMine: false,
    favorited: false,
  },
  {
    id: "vault_matic_usdc_005",
    name: "MATIC-USDC 0.05%",
    address: "0x6ac8e19",
    token0Symbol: "MATIC",
    token1Symbol: "USDC",
    feeTierLabel: "0.05%",
    pairType: "volatile",
    chainId: "polygon",
    chainName: "Polygon",
    dexId: "quickswap",
    dexName: "QuickSwap",
    tvlUsd: 2198000,
    tvlChange24hPct: 4.4,
    apyPct: 21.8,
    aprPct: 19.3,
    status: "active",
    rangeStatus: "above",
    hasGauge: true,
    isMine: false,
    favorited: false,
  },
];